TOOLS = [
    {
        "title": "Merge PDF",
        "short_title": "Merge PDF",
        "description": "Merge multiple PDF files into one directly in your browser. No uploads, no accounts, no tracking.",
        "meta_description": "Merge PDF files online privately. Combine multiple PDFs directly in your browser with no uploads, no accounts, and no tracking.",
        "og_title": "Merge PDF Online Privately - TrustPDF",
        "og_description": "Combine multiple PDF files directly in your browser. Private, client-side PDF merging with no uploads.",
        "url_name": "pages:merge_pdf",
        "path": "/merge-pdf/",
        "icon": "img/icons/merge-pdf.png",
        "og_image": "img/og/merge-pdf-og.png",
        "group": "Files",
        "keywords": "merge pdf, combine pdf, pdf merger, private pdf merger, client-side pdf tool",
        "template_name": "merge_pdf.html",
    },
    {
        "title": "Split PDF",
        "short_title": "Split PDF",
        "description": "Extract selected pages or page ranges from a PDF directly in your browser.",
        "meta_description": "Split PDF files online privately. Extract pages or page ranges directly in your browser with no uploads, no accounts, and no tracking.",
        "og_title": "Split PDF Online Privately - TrustPDF",
        "og_description": "Extract pages from PDF files directly in your browser. No uploads, no storage, no tracking.",
        "url_name": "pages:split_pdf",
        "path": "/split-pdf/",
        "icon": "img/icons/split-pdf.png",
        "og_image": "img/og/split-pdf-og.png",
        "group": "Pages",
        "keywords": "split pdf, extract pdf pages, pdf splitter, private pdf splitter, client-side pdf tool",
        "template_name": "split_pdf.html",
    },
    {
        "title": "Rotate PDF Pages",
        "short_title": "Rotate Pages",
        "description": "Rotate selected pages or all pages in a PDF directly in your browser.",
        "meta_description": "Rotate PDF pages online privately. Rotate selected pages or all pages directly in your browser with no uploads or tracking.",
        "og_title": "Rotate PDF Pages Privately - TrustPDF",
        "og_description": "Rotate PDF pages directly in your browser. Your files stay on your device.",
        "url_name": "pages:rotate_pdf_pages",
        "path": "/rotate-pdf-pages/",
        "icon": "img/icons/rotate-pdf-pages.png",
        "og_image": "img/og/rotate-pdf-pages-og.png",
        "group": "Pages",
        "keywords": "rotate pdf, rotate pdf pages, pdf page rotation, private pdf tool",
        "template_name": "rotate_pdf_pages.html",
    },
    {
        "title": "Remove PDF Pages",
        "short_title": "Remove Pages",
        "description": "Remove unwanted pages from a PDF file directly in your browser.",
        "meta_description": "Remove pages from PDF files online privately. Delete unwanted PDF pages directly in your browser with no uploads.",
        "og_title": "Remove PDF Pages Privately - TrustPDF",
        "og_description": "Delete unwanted pages from PDF files directly in your browser. No uploads, no accounts, no tracking.",
        "url_name": "pages:remove_pdf_pages",
        "path": "/remove-pdf-pages/",
        "icon": "img/icons/remove-pdf-pages.png",
        "og_image": "img/og/remove-pdf-pages-og.png",
        "group": "Pages",
        "keywords": "remove pdf pages, delete pdf pages, pdf page remover, private pdf editor",
        "template_name": "remove_pdf_pages.html",
    },
    {
        "title": "Reorder PDF Pages",
        "short_title": "Reorder Pages",
        "description": "Drag and reorder PDF pages, then export the new file directly in your browser.",
        "meta_description": "Reorder PDF pages online privately. Drag pages into a new order and export the PDF directly in your browser.",
        "og_title": "Reorder PDF Pages Privately - TrustPDF",
        "og_description": "Rearrange PDF pages directly in your browser. Private, client-side PDF page reordering.",
        "url_name": "pages:reorder_pdf_pages",
        "path": "/reorder-pdf-pages/",
        "icon": "img/icons/reorder-pdf-pages.png",
        "og_image": "img/og/reorder-pdf-pages-og.png",
        "group": "Pages",
        "keywords": "reorder pdf pages, rearrange pdf, organize pdf pages, private pdf tool",
        "template_name": "reorder_pdf_pages.html",
    },
    {
        "title": "PDF Metadata Viewer",
        "short_title": "Metadata Viewer",
        "description": "Inspect common PDF document properties and metadata directly in your browser.",
        "meta_description": "View PDF metadata online privately. Inspect PDF document properties directly in your browser with no uploads.",
        "og_title": "PDF Metadata Viewer - TrustPDF",
        "og_description": "Inspect PDF metadata and document properties directly in your browser. No uploads or tracking.",
        "url_name": "pages:pdf_metadata_viewer",
        "path": "/pdf-metadata-viewer/",
        "icon": "img/icons/pdf-metadata-viewer.png",
        "og_image": "img/og/pdf-metadata-viewer-og.png",
        "group": "Metadata",
        "keywords": "pdf metadata viewer, view pdf properties, inspect pdf metadata, private pdf tool",
        "template_name": "pdf_metadata_viewer.html",
    },
    {
        "title": "PDF Metadata Editor",
        "short_title": "Metadata Editor",
        "description": "Edit common PDF metadata fields directly in your browser.",
        "meta_description": "Edit PDF metadata online privately. Change PDF title, author, subject, and keywords directly in your browser.",
        "og_title": "PDF Metadata Editor - TrustPDF",
        "og_description": "Edit PDF metadata directly in your browser. Private, client-side PDF metadata editing.",
        "url_name": "pages:pdf_metadata_editor",
        "path": "/pdf-metadata-editor/",
        "icon": "img/icons/pdf-metadata-editor.png",
        "og_image": "img/og/pdf-metadata-editor-og.png",
        "group": "Metadata",
        "keywords": "pdf metadata editor, edit pdf properties, change pdf title, private pdf editor",
        "template_name": "pdf_metadata_editor.html",
    },
    {
        "title": "Images to PDF",
        "short_title": "Images to PDF",
        "description": "Convert JPG and PNG images into a PDF file directly in your browser.",
        "meta_description": "Convert images to PDF online privately. Turn JPG and PNG images into a PDF directly in your browser with no uploads.",
        "og_title": "Images to PDF Privately - TrustPDF",
        "og_description": "Convert JPG and PNG images into a PDF directly in your browser. No uploads, no accounts, no tracking.",
        "url_name": "pages:images_to_pdf",
        "path": "/images-to-pdf/",
        "icon": "img/icons/images-to-pdf.png",
        "og_image": "img/og/images-to-pdf-og.png",
        "group": "Conversion",
        "keywords": "images to pdf, jpg to pdf, png to pdf, convert image to pdf, private pdf converter",
        "template_name": "images_to_pdf.html",
    },
]

STATIC_PAGES = {
    "index": {
        "title": "TrustPDF",
        "seo_title": "TrustPDF - Private Client-Side PDF Tools",
        "description": "Private client-side PDF tools. Merge, split, rotate, reorder, inspect, edit, and convert PDF files directly in your browser.",
        "meta_description": "TrustPDF provides private client-side PDF tools. Work with PDF files directly in your browser with no uploads, no accounts, and no tracking.",
        "og_title": "TrustPDF - Private Client-Side PDF Tools",
        "og_description": "Merge, split, rotate, reorder, inspect, edit, and convert PDF files directly in your browser.",
        "og_image": "img/og/trustpdf-og.png",
    },

    "about": {
        "title": "About",
        "seo_title": "About TrustPDF - Private Open Source PDF Tools",
        "description": "Learn about TrustPDF, a privacy-first open source PDF tool created to process PDF files directly in your browser.",
        "meta_description": "Learn about TrustPDF, a privacy-first open source PDF tool for working with PDF files directly in your browser with no uploads, no accounts, and no tracking.",
        "og_title": "About TrustPDF",
        "og_description": "TrustPDF is a privacy-first open source PDF tool built for simple client-side PDF processing directly in your browser.",
        "og_image": "img/og/trustpdf-og.png",
    },

    "privacy_policy": {
        "title": "Privacy Policy",
        "seo_title": "Privacy Policy - TrustPDF",
        "description": "Read the TrustPDF privacy policy. Learn how TrustPDF protects your files by processing PDF documents directly in your browser.",
        "meta_description": "TrustPDF is a privacy-first PDF tool. Read our privacy policy and learn how files are processed directly in your browser with no uploads and no accounts.",
        "og_title": "Privacy Policy - TrustPDF",
        "og_description": "Learn how TrustPDF protects your privacy with client-side PDF processing, no uploads, no accounts, and no unnecessary tracking.",
        "og_image": "img/og/trustpdf-og.png",
    },

    "cookie_policy": {
        "title": "Cookie Policy",
        "seo_title": "Cookie Policy - TrustPDF",
        "description": "Read the TrustPDF cookie policy. Learn how TrustPDF uses minimal, privacy-friendly analytics without third-party cookies.",
        "meta_description": "Read the TrustPDF cookie policy. TrustPDF uses no third-party cookies and keeps PDF processing private and client-side.",
        "og_title": "Cookie Policy - TrustPDF",
        "og_description": "Learn about TrustPDF's cookie policy and privacy-friendly approach to analytics, cookies, and client-side PDF processing.",
        "og_image": "img/og/trustpdf-og.png",
    },

    "privacy_tools": {
        "title": "Privacy Tools",
        "seo_title": "Privacy Tools - TrustPDF",
        "description": "Explore privacy-focused tools and services, including Proton products for email, VPN, password management, cloud storage, and online privacy.",
        "meta_description": "Discover privacy-focused tools promoted by TrustPDF, including Proton products for private email, VPN, password management, cloud storage, and online privacy.",
        "og_title": "Privacy Tools - TrustPDF",
        "og_description": "Explore privacy-focused tools and Proton products for safer email, VPN, password management, cloud storage, and everyday online privacy.",
        "og_image": "img/og/privacy-tools-og.png",
    },
}